package Main.state;

public enum BotState {
    WAIT_STATUS,
    WAIT_CHANGE_DAY,
    DAY_RECEIVED,
    BUTTON_ADD,
    BUTTON_AWEEK,
    BUTTON_CHOICE,
    BUTTON_CHANGE,
    CHANGE_SCHEDULE,
    SET_ACTUAL_TABLENAME,
    END
}